/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Transcription {
  text: string
  srt: string
}
export declare class MutterModel {
  constructor(modelPath: string)
  transcribe(audioPath: string): Promise<Transcription>
}
